### ISSUE TITLE
makefile.in is missing

### ISSUE THREAD

**Issue by wpoely86** [gjbex/atools#15]
I need to run `autoreconf -f` before I can run the configure script.

Can the 1.4.1 release also be tagged?

**Comment by gjbex** [comment]
Issue should be resolved in 1.4.1 release, which is now also tagged as such.

Thanks for pointing it out.

**Comment by wpoely86** [comment]
Unfortunately, it's not in the 1.4.1 releases. Can you tag another one?

**Comment by gjbex** [comment]
Ok, so if you delete a release, commit and do a release with the same name,
Github forgets about the new commits... oh well.

Thanks, best regards, -gjb-
