### ISSUE TITLE
Problem with acreate 

### ISSUE THREAD

**Issue by sbecuwe** [gjbex/atools#18]
Hello Geert Jan

I'm using the GitHub version and a system Python 2.7.5.

Following command is executed without problems
`./acreate ../examples/standard.pbs --data ../examples/data.csv`
but
`./acreate --data ../examples/data.csv ../examples/standard.pbs`
returns 
`acreate.py: error: too few arguments`

Since the problem seems to be related to `nargs='*'` for `--data` I would suggest to update the documentation and write the above as 
`./acreate --data ../examples/data.csv -- ../examples/standard.pbs`

Regards
Stefan

**Comment by sbecuwe** [comment]
P.S. acreate should be added to bin/Makefile.am

**Comment by gjbex** [comment]
Thanks @sbecuwe, both issues should be fixed by #19 and #bugfix/install
