### ISSUE TITLE
arange on single column data, "Could not determine delimiter"

### ISSUE THREAD

**Issue by RVerschoren** [gjbex/atools#29]
Hi,

I noticed the following issue when running through the example files, using atools 1.4.7 (Github `tar.gz` file) with system Python 2.7.5. I verified this on another (Linux) system with a newly download copy of atools 1.4.7 and system Python 2.7.18.

On the single_column_data.csv file in the `examples/` directory, `aenv` runs successfully using the _--no_sniffer_ option:
`PBS_ARRAYID=1 ./aenv --no_sniffer --data ../examples/single_column_data.csv`
and returns the expected result
>export file="./abc.txt"

However, when running `arange` on the same file, using the same options:
`./arange --no_sniffer --data ../examples/single_column_data.csv`
I get the following error:
>Traceback (most recent call last):
  File "<atools_dir>/bin/../lib/arange.py", line 42, in <module>
    sniff=options.sniff, no_sniffer=options.no_sniffer
  File "<atools_dir>/lib/vsc/atools/work_analysis.py", line 60, in compute_items_todo
    todo = _compute_data_ids(data_files, sniff)
  File "<atools_dir>/lib/vsc/atools/work_analysis.py", line 40, in _compute_data_ids
    dialect = sniffer.sniff(csv_file.read(sniff))
  File "/usr/lib64/python2.7/csv.py", line 188, in sniff
    raise Error, "Could not determine delimiter"
_csv.Error: Could not determine delimiter

`arange` sometimes does work on single column files, albeit for the wrong reason. For single column files, `arange` seems to return the correct result only if the first letter of the first data line is equal to the first letter of the column heading. For example, running `arange --no_sniffer --data <file>` on a file with following content
>f
a

returns the above error, where running it on a file with following content
>f
f

successfully returns 1. Hence, this is likely related to the way the delimiter is detected by `arange`, especially because `aenv` works as expected in both cases.

Adding `no_sniffer` as a third argument in the call to `_compute_data_ids` on line 60 of `lib/vsc/atools/work_analysis.py` fixed it for me. As I'm currently unaware of possible consequences in the rest of the code, I have not yet submitted this as a pull request.

**Comment by gjbex** [comment]
Sorry this took a while to address, I didn't notice the isssue.

It has been fixed in the 1.4.8 release.  The solution you suggested is implemented.
